# Generated by Django 5.0.6 on 2024-06-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_user_brand_name_user_name_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='categories',
            field=models.ManyToManyField(related_name='categories_set', to='admin_app.category'),
        ),
        migrations.AlterField(
            model_name='show',
            name='genres',
            field=models.ManyToManyField(related_name='genres_set', to='admin_app.genre'),
        ),
    ]
