# Generated by Django 5.0.6 on 2024-06-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_show_categories_alter_show_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='brand_image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
