# Generated by Django 5.0.6 on 2024-05-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_category_genre_video_genre_videos_category_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='videos',
        ),
    ]
