# Generated by Django 5.0.6 on 2024-05-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_category_slug_genre_slug_video_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
    ]
